title: HERMES
email: your-email@domain.com
contact: Your Name
description: > # this means to ignore newlines
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
github_org: health-economics-in-r
plugins:
  - jekyll-octicons
header_pages:
  - about.md
  - projects.md
  - people.md
  - events.md
